name: Generate Stats Images
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight
  workflow_dispatch: # Allows manual run
  push: {branches: ["main"]}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Language & Stats Cards
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.STATS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
